### ISSUE TITLE
Add support to look for new commits in a branch for git repos

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/zeitgeist#27]
#### What would you like to be added:
Zeitgeist should also support looking up for new commits on branch in a git repo.

#### Why is this needed:
The `--remote` feature of Zeitgeist is used by some systems to monitor for availability of new changes/versions of multiple projects.
Automated builds systems are an example of such systems. Automated build systems might choose to monitor a collection of projects to make new builds. The triggers for such systems can include being able to monitor for changes to a branch of a git project.
Adding the support to look for/monitor changes to a git branch through zeitgeist will allow of a system to monitor a collection of projects (git projects) and resources (AMIs) in a unified way.
Example:
```
dependencies:
- name: awesome-cli
  version: 79b5b78183f2585689780fbdef1395b06d05ed25
  scheme: random
  upstream:
    flavour: github
    url: project/awesome-cli
    branch: master
- name: terraform
  version: 0.12.3
  upstream:
    flavour: github
    url: hashicorp/terraform
- name: fluentd-chart
  version: 2.1.1
  sensitivity: major
  upstream:
    flavour: helm
    repo: stable
    name: fluentd
- name: aws-eks-ami
  version: ami-09bbefc07310f7914
  scheme: random
  upstream:
    flavour: ami
    owner: amazon
    name: "amazon-eks-node-1.13-*"
```
Using a configuration like this a system can be used to detect changes to any of the interested projects and perform corresponding actions.
