### ISSUE TITLE
Formatted output for extensibility

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/zeitgeist#30]
#### What would you like to be added:
I would like to add support for formatted outputs like `yaml` and `json`. As mentioned in #21 and #27 Zeitgeist can be used by other systems that rely on the output of Zeitgeist to perform some actions. To allow smoother integrations with other systems, eg: build system, dependency bots, etc, we need a machine readable output.

Example: 
For the following `dependency.yaml` :
```yaml
dependencies:
- name: terraform 
  version: 0.12.3
  upstream:
    flavour: github
    url: hashicorp/terraform
- name: awesome-cli
  version: 79b5b78183f2585689780fbdef1395b06d05ed25
  scheme: random
  upstream:
    flavour: github
    url: project/awesome-cli
    branch: master
```
The output (in yaml format) can be :
```yaml
- name: terraform  # example of a component where a new version is detected
  version: 0.12.3
  nextVersion: 0.14.7 # new version available that satisfies the given constraints
- name: awesome-cli  # example of a component where no new version is detected
  version: 79b5b78183f2585689780fbdef1395b06d05ed25
  nextVersion: 79b5b78183f2585689780fbdef1395b06d05ed25
```

The output format can be specified by `--output-format` and the accepted values will be `json` and `yaml`.   
Would also be better to add a `-o` flag to support writing the output to a target file. Would default to writing the output to `dependency_output.(yaml|json)`

#### Why is this needed:

 As mentioned in #21 and #27 Zeitgeist can be used by other systems that rely on the output of Zeitgeist to perform some actions. To allow smoother integrations with other systems, eg: build system, dependency bots, etc, we need a machine readable output.
 
 
 Additional note:  
An issue along the same lines is recorded at #21. This issue will be used to track the efforts on this feature as it is going to cover a broader list of output formats, namely `yaml` and `json`.
