### ISSUE TITLE
Zeitgeist fails to validate OCI Helm repositories

### ISSUE THREAD

**Issue by Pluies** [kubernetes-sigs/zeitgeist#410]
#### What happened:

When using an [OCI repository](https://helm.sh/docs/topics/registries/) as a Helm upstream, like:
```
dependencies:
  - name: karpenter
    version: 0.22.1
    scheme: semver
    upstream:
      chart: karpenter
      flavour: helm
      repo: oci://public.ecr.aws/karpenter
    refPaths:
      - path: karpenter.tf
        match: zeitgeist:karpenter
```

Zeitgeist fails:
```
level=error msg="failed to download index file for repo oci://public.ecr.aws/karpenter"
level=fatal msg="error during command execution: &fmt.wrapError{msg:\"upgrade dependencies: object required\", err:(*errors.errorString)(0xc000b0d850)}"
```

#### What you expected to happen:

Zeitgeist ought to work like for non-OCI based Helm repositories.

#### How to reproduce it (as minimally and precisely as possible):

See above.

#### Anything else we need to know?:

n/a

#### Environment:

n/a
