### ISSUE TITLE
Add support for upgrading a single dependency - to support dependabot/renovate like workflows

### ISSUE THREAD

**Issue by chlunde** [kubernetes-sigs/zeitgeist#810]
#### What would you like to be added:
One of the following:
1. `zeitgeist upgrade [dependency-name]`
2. `zeitgeist upgrade [dependency-name1...] [dependency-name2...]`
3. `zeitgeist upgrade [dependency-fnmatch1...] [dependency-fnmatch2...]`

I think the first option is simplest and it can be extended to the two other options if needed anyway

It can also support up/downgrading to a specific version like `zeitgeist upgrade kustomize --to-version=5.0.3`, but that may be better handled by a command like `zeitgeist set-version [dependency-name] [version]`

#### Why is this needed:
I would like to have a scheduled job that creates PRs like dependabot for our GitOps based repository with Kustomize yaml files or anything else that dependabot/renovate does not support with the flexibility zeitgeist gives us.

I can implement the code, but I've created this issue so we can agree on the correct design first. Maybe it's best to start with `set-version`?

**Comment by chlunde** [comment]
cc @ykakarap

**Comment by chlunde** [comment]
@Pluies do you have any inputs here? Flags are of course also an alternative.

**Comment by Pluies** [comment]
I like the idea of `set-version` more than `upgrade ... --to-version=` as the idea behind `upgrade` is to let Zeitgeist pick the latest release (modulo semver constraints).

I'd be happy to see both `zeitgeist set-version [dependency-name] [version]` and `zeitgeist upgrade [dependency-name]` (with an arbitrary number of dependencies, the default when no args being all dependencies as currently) :)

**Comment by chlunde** [comment]
@Pluies cool, I've added a PR here: #818. We've also tested it in a scheduled github action to create PRs for each individual upgrade using a matrix

**Comment by Pluies** [comment]
Added comment on the PR!

As a general aside on the `set-version` command, I've found myself building zeitgeist with it locally to use it, it's very handy 👍  My own use case was:
- Running `zeitgeist upgrade` in CI, which opens a PR
- Realise one of the updates involves a breaking change that we want to keep separate, or extra prep work, etc
- Run `zeitgeist set-version unwanted-update $previous-version` to bring it back, and call it a day 👍

**Comment by chlunde** [comment]
@Pluies I'm happy with the functionality as is, so unless you would like a different behaviour, I think we can close this issue.

Pasting some relevant lines from a github action, which might be helpful if someone else wants to create a PR per dependency:

```yaml
name: zeitgeist

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: 0 3 * * MON
  workflow_dispatch: {}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  zeitgeist-run:
    outputs:
      MATRIX: ${{ steps.zeitgeist.outputs.MATRIX }}

...
zeitgeist export --output-file dependency_output.json --output-format json
echo "MATRIX=$(jq --compact-output '{ "include": . }' < dependency_output.json)" >> "$GITHUB_OUTPUT"

  zeitgeist-per-dependency:
    needs: zeitgeist-run
    strategy:
      matrix: ${{fromJson(needs.zeitgeist-run.outputs.MATRIX)}}
      fail-fast: false
      max-parallel: 1
...

      - name: Run zeitgeist
        run: |
          git checkout master

          zeitgeist set-version ${{ matrix.name }} ${{ matrix.new_version }}

          echo
          echo "Diff after set-version:"
          git diff

          echo
          echo "Changed dirs"
          git diff --name-only | xargs dirname | sort | uniq

          git status
      - name: Push and create PR
        env:
          GH_TOKEN: ${{ github.token }}
        timeout-minutes: 10
        run: |
          git config --global user.email "noreply@...."
          git config --global user.name "Zeitgeist Bot"

          branch="zeitgeist_${{ matrix.name }}"

          if git ls-remote --exit-code --heads origin refs/heads/$branch; then
              printf ":x: Remote branch already exists!\n"
              exit 1
          fi

          git checkout -b "$branch"
          git commit -a -m "Update ${{ matrix.name }} from ${{ matrix.version }} to ${{ matrix.new_version }}"

          git push --force --set-upstream origin "$branch"

          gh pr create --label "dependencies" --title "Update ${{ matrix.name }} from ${{ matrix.version }} to ${{ matrix.new_version }}" --body "Zeitgeist"
 ```
